############################ GENERAL SETTINGS ############################
#----- SNS ARN -----#
successNotifierSNSARN: <SUCCESS-NOTIFIER-SNS-ARN>
failureNotifierSNSARN: <FAILURE-NOTIFIER-SNS-ARN>

#----- SLACK CHANNEL WEBHOOKS -----#
successSlackChannel: <SUCCESS_SLACK_CHANNEL>
failureSlackChannel: <FAILURE_SLACK_CHANNEL>
