service: codeBuild

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  success-notifier:
    handler: handler.hello
    events:
      - sns: ${file(./config.yml):successNotifierSNSARN}
