service: codeBuild

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  environment:
    SUCCESS_SLACK_CHANNEL: ${file(./config.yml):successSlackChannel}
    FAILURE_SLACK_CHANNEL: ${file(./config.yml):failureSlackChannel}

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true # enable auto including node_modules
  graphiql:
    babelOptions:
      presets: [es2015, es2016, stage-0]
      plugins: [transform-runtime]

functions:
  success-notifier:
    handler: handler.successNotifier
    events:
      - sns: ${file(./config.yml):successNotifierSNSARN}

  failure-notifier:
    handler: handler.failureNotifier
    events:
      - sns: ${file(./config.yml):failureNotifierSNSARN}
